# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
