# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('star', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('url', models.URLField(default='https://www.agoda.com')),
                ('image_url', models.URLField(default='https://www.agoda.com')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Unknown', 'Unknown'), ('Location', 'Location'), ('Price', 'Price'), ('Room Size', 'Room Size'), ('Facilities', 'Facilities'), ('Staff', 'Staff'), ('Security', 'Security'), ('General', 'General')], default='Unknown', max_length=100)),
                ('method', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('content', models.CharField(default='', max_length=2500)),
                ('rating', models.FloatField(default=0)),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Hotel')),
                ('label', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Hotel_Label')),
            ],
        ),
    ]
